### ISSUE TITLE
Test fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by Tybion** [florianf/tileoven#4]
I downloaded the code today.  Install seemed to complete fine, although there were a lot of warnings in part of the output ..

```
npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json backbone@0.3.3 No repository field.
npm WARN package.json backbone-dirty@1.1.3 No description
npm WARN package.json backbone-dirty@1.1.3 No repository field.
npm WARN package.json bcrypt-pbkdf@1.0.0 No repository field.
npm WARN package.json bones@1.3.30 No repository field.
npm WARN package.json dirty@0.9.9 No repository field.
npm WARN package.json jshint@0.2.3 No repository field.
npm WARN package.json mirror@0.3.3 No description
npm WARN package.json mirror@0.3.3 No repository field.
npm WARN package.json modestmaps@3.3.5 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.
npm WARN package.json tiletype@0.1.0 No repository field.
npm WARN package.json uglify-js@1.0.2 No description
```
Versions ..
```
$ npm --version
3.5.2
$ node --version
v4.2.6
$ nodejs --version
v4.2.6
```

Results of test ..
```
$ npm test

> tilemill@0.10.2 test /home/david/tileoven
> mocha --timeout 100000

Creating configuration dir /home/david/tileoven/test/fixtures/files/.tilemill
Creating export dir /home/david/tileoven/test/fixtures/files/export
Creating cache dir /home/david/tileoven/test/fixtures/files/cache
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
  abilities
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ GET should return JSON

  config
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ GET should return JSON (85ms)
    ✓ PUT should update config
    ✓ GET should return updated config
    ✓ PUT should 409 on invalid config
    1) DELETE should 409

  datasource
    2) "before all" hook
    3) "after all" hook

  config loading pwnage
    ✓ there should only be one optimist module otherwise you are hosed (850ms)
    ✓ there should only be one sqlite3 module otherwise you are hosed (837ms)
    ✓ there should only be one mapnik module otherwise you are hosed (827ms)

  export
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ PUT should create export job
    ✓ GET should retrieve export job
    4) DELETE should stop export job
    ✓ PUT create export job spanning the anti-meridian
[tilemill-ui] Exporting format: mbtiles
[tilemill-ui] Exporting format: mbtiles
[tilemill-ui] Rendering export
[tilemill-ui] Persisting state in /home/david/tileoven/test/fixtures/files/export/demo_anti-meridian.export every minute
[tilemill-ui] Persisting state in /home/david/tileoven/test/fixtures/files/export/demo_anti-meridian.export every minute
[tilemill-ui] Completing export process
[tilemill-ui] Exiting process [tm-demo_anti-meridian.mbtiles]
{ progress: 1,
  status: 'complete',
  id: '14771157350301',
  format: 'mbtiles',
  project: 'demo_01',
  tile_format: 'png',
  filename: 'demo_anti-meridian.mbtiles',
  bbox: [ 175, 31.8402, -175, 71.9245 ],
  minzoom: 0,
  maxzoom: 2,
  pid: 22652,
  created: 1477115738588,
  remaining: 0,
  updated: 1477115754039,
  rate: 40 }
    ✓ GET anti-meridian job to see if it succeeded (16173ms)
    5) DELETE should remove anti-meridian export job
    6) GET should find no export jobs

  project
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ collection should list projects
    ✓ model should load JSON
    ✓ model should not have an update
    ✓ model should have an update
    ✓ PUT should create a project
    ✓ GET should load created project
    7) DELETE should remove project
    ✓ PUT should fail with invalid id
    ✓ PUT should fail with invalid stylesheet

  tile endpoint
Note: Unknown option "host" in config file.
Plugin [carto] loaded.
Plugin [editor] loaded.
Plugin [fonts] loaded.
Plugin [templates] loaded.
Started [Server Core:20009].
Started [Server Tile:20008].
    ✓ should 404 for missing project
    ✓ should 200 (tile) for existing project (86ms)
    ✓ should 200 (grid) for existing project (75ms)


  23 passing (20s)
  7 failing

  1) config DELETE should 409:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:202:15)
      at Socket.socketOnEnd (_http_client.js:287:23)
      at endReadableNT (_stream_readable.js:905:12)

  2) datasource "before all" hook:
     Uncaught Error: Command failed: /bin/sh -c         psql -d postgres -c "DROP DATABASE IF EXISTS tilemill_test;" ;         createdb -E UTF8 -T template_postgis tilemill_test ;          psql -d tilemill_test -f /home/david/tileoven/test/fixtures/tilemill_test.sql
psql: FATAL:  role "david" does not exist
createdb: could not connect to database template1: FATAL:  role "david" does not exist
psql: FATAL:  role "david" does not exist

      at ChildProcess.exithandler (child_process.js:213:12)
      at maybeClose (internal/child_process.js:821:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

  3) datasource "after all" hook:
     TypeError: Cannot read property 'close' of undefined
      at Context.<anonymous> (test/datasource.test.js:24:9)

  4) export DELETE should stop export job:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:202:15)
      at Socket.socketOnEnd (_http_client.js:287:23)
      at endReadableNT (_stream_readable.js:905:12)

  5) export DELETE should remove anti-meridian export job:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:202:15)
      at Socket.socketOnEnd (_http_client.js:287:23)
      at endReadableNT (_stream_readable.js:905:12)

  6) export GET should find no export jobs:

      Uncaught AssertionError: [] deepEqual [ { progress: 0,
    status: 'processing',
    id: '1477115735030',
    format: 'mbtiles',
    project: 'demo_01',
    tile_form
      + expected - actual

      -[]
      +[
      +  {
      +    "bbox": [
      +      -29.5642
      +      31.8402
      +      42.1545
      +      71.9245
      +    ]
      +    "created": 1477115738570
      +    "filename": "demo_01.mbtiles"
      +    "format": "mbtiles"
      +    "id": "1477115735030"
      +    "maxzoom": 2
      +    "minzoom": 0
      +    "pid": 22647
      +    "progress": 0
      +    "project": "demo_01"
      +    "status": "processing"
      +    "tile_format": "png"
      +  }
      +  {
      +    "bbox": [
      +      175
      +      31.8402
      +      -175
      +      71.9245
      +    ]
      +    "created": 1477115738588
      +    "filename": "demo_anti-meridian.mbtiles"
      +    "format": "mbtiles"
      +    "id": "14771157350301"
      +    "maxzoom": 2
      +    "minzoom": 0
      +    "pid": 22652
      +    "progress": 1
      +    "project": "demo_01"
      +    "rate": 40
      +    "remaining": 0
      +    "status": "complete"
      +    "tile_format": "png"
      +    "updated": 1477115754039
      +  }
      +]
      
      at test/export.test.js:162:16
      at IncomingMessage.<anonymous> (test/support/start.js:165:13)
      at endReadableNT (_stream_readable.js:905:12)

  7) project DELETE should remove project:
     Uncaught Error: socket hang up
      at createHangUpError (_http_client.js:202:15)
      at Socket.socketOnEnd (_http_client.js:287:23)
      at endReadableNT (_stream_readable.js:905:12)

npm ERR! Test failed.  See above for more details.
```

**Comment by florianf** [comment]
Thanks for the report. Tests are currently failing on nodejs > 0.12, don't know why. Upstream also has this problem, I couldn't find the root cause.
